name: qychatapp
description: A flutter qychatapp project created using MobX and Provider.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.

version: 1.0.0-dev.4

homepage: https://github.com/hyyz3293/QyChatApp.git
repository: https://github.com/hyyz3293/QyChatApp.git

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # A
  another_flushbar: ^1.12.29
  adaptive_navigation: ^0.0.3
  audio_session: ^0.1.21 # 音频
  android_intent_plus: ^4.0.3
  audioplayers: ^6.1.0
  audio_waveforms: ^1.0.5
  any_link_preview: ^3.0.2
  # B
  flutter_blue_plus: ^1.31.15
  # C
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  crop_your_image: ^1.1.0
  crypto: ^3.0.6
  # D
  dio: ^5.7.0
  date_format: ^2.0.2 #日期管理类
  # E
  event_bus: ^2.0.0
  emoji_picker_flutter: ^3.0.0
  # F
  flutter_mobx: ^2.0.6+5
  flutter_slidable: ^3.0.1
  flutter_image_compress: ^2.3.0
  flutter_lorem: ^2.0.0
  flutter_html: ^3.0.0-alpha.6  # 3.x版本可能已解决依赖冲突
  flutter_markdown: ^0.7.7+1
  flutter_link_previewer: ^3.2.2
  # G
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  go_router: ^14.3.0
  gif: ^2.3.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  # H
  http: ^1.1.1
  # I
  intl: ^0.19.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  in_app_update: ^4.2.3
  # J
  json_serializable: ^6.6.1
  # K
  # L
  localstorage: ^4.0.0+1
  logger: ^2.0.0
  # M
  mobx: ^2.1.4
  # N
  # O
  oktoast: ^3.4.0
  open_file: ^3.5.10
  # P
  path_provider: ^2.0.14
  path: ^1.8.0
  permission_handler: ^11.3.0
  package_info_plus: ^8.0.0
  photo_manager: ^3.2.3
  pull_to_refresh: ^2.0.0
  percent_indicator: ^4.2.4
  pull_down_button: ^0.10.2
  provider: ^6.0.5 # 状态管理
  # Q
  qr_flutter: ^4.1.0
  # R
  reorderables: ^0.6.0
  record: ^6.0.0
  # S
  shared_preferences: ^2.2.3
  sembast_web: ^2.1.3
  sembast: ^3.4.4
  sqflite: ^2.3.3
  share_plus: ^7.1.0
  scrollable_positioned_list: ^0.3.8
  socket_io_client: ^1.0.2 #">=1.0.2 <3.0.0"
  # T
  timeago: ^3.7.0
  # U
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  # V
  validators: ^3.0.0
  vibration: ^2.0.1
  video_player: ^2.9.5
  # W
  webview_flutter: ^4.13.0
  web_socket_channel: ^3.0.3
  # X
  xxtea: ^2.1.0
  # Y
  # Z

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.14.1
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3
  analyzer: ^5.10.0

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true


# For information on the generic Dart art of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/ring.aac
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
